import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/Header";
import Footer from "./components/Footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Explore Edu Reisen",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen">
        <Header />
        {children}
        <Footer />

        </div>
  <script type="text/javascript" id="hs-script-loader" async defer src="//js-eu1.hs-scripts.com/144030023.js"></script>
      </body>
    </html>
  );
}
